'use strict';

const morgan = require('morgan');
const winston = require('winston');

/**
 * Winston logger instance used for HTTP request logging.
 * Logs are written to stdout (and to files in non-test environments).
 */
const logger = winston.createLogger({
  level: process.env.LOG_LEVEL || 'info',
  format: winston.format.combine(
    winston.format.timestamp(),
    winston.format.errors({ stack: true }),
    winston.format.json()
  ),
  transports: [
    new winston.transports.Console({
      silent: process.env.NODE_ENV === 'test',
    }),
  ],
});

/**
 * Morgan stream that writes to the Winston logger.
 */
const stream = {
  write(message) {
    // Morgan appends a newline; strip it before handing to Winston
    logger.http(message.trimEnd());
  },
};

/**
 * Morgan token: request id from X-Request-ID header (set by upstream proxy or
 * generated by the client).
 */
morgan.token('request-id', (req) => req.headers['x-request-id'] || '-');

/**
 * Morgan token: authenticated user id (populated by authenticate middleware).
 */
morgan.token('user-id', (req) => (req.user && req.user.id ? String(req.user.id) : '-'));

/**
 * Morgan format string.
 * Example output:
 *   GET /api/products 200 45ms - request-id=abc123 user-id=42
 */
const FORMAT =
  ':method :url :status :response-time ms - request-id=:request-id user-id=:user-id';

/**
 * HTTP request logger middleware.
 * Uses Morgan with a combined format piped through Winston.
 * Skip logging in the test environment to keep test output clean.
 */
const requestLogger = morgan(FORMAT, {
  stream,
  skip: () => process.env.NODE_ENV === 'test',
});

module.exports = requestLogger;
module.exports.logger = logger;
